### ISSUE TITLE
Make disable when score is zero

### ISSUE THREAD

**Issue by enderahmetyurt** [lxxxvi/tippkick.club#115]
If score is zero, the minus button should be disabled, I mean not clickable. It should not be bold pink. What do u think @lxxxvi 
We can add a css preference to make disable pointer events if score is zero.

<img width="611" alt="Screen Shot 2021-05-30 at 19 58 50" src="https://user-images.githubusercontent.com/447588/120113101-9e8e4d00-c181-11eb-8fad-f1c189563530.png">

**Comment by enderahmetyurt** [comment]
ooh I've seen now https://github.com/lxxxvi/tippkick.club/blob/main/app/components/bet_component.html.haml#L24 `disabled: @bet.home_team_score&.zero?` I guess it's not working. I should be `pointer-events: none` or something.

**Comment by lxxxvi** [comment]
@enderahmetyurt
🤔 Good find, thank you. I'll try looking into it this afternoon/evening.

**Comment by lxxxvi** [comment]
@enderahmetyurt Also... why does **Turkey** have 0 scores (see your screenshot)? That's impossible, no? 😉

**Comment by lxxxvi** [comment]
@enderahmetyurt Thanks for reporting this, I think it improves usability!
