### ISSUE TITLE
Edit score from an input

### ISSUE THREAD

**Issue by enderahmetyurt** [lxxxvi/tippkick.club#117]
Why do we need to click minus or plus to control score? Should we write to directly score in an input?

<img width="1259" alt="Screen Shot 2021-06-01 at 14 05 45" src="https://user-images.githubusercontent.com/447588/120313341-7e29d400-c2e2-11eb-87b9-279e8f701703.png">

**Comment by lxxxvi** [comment]
@enderahmetyurt 
The game is primarily designed for mobile users. The first time I built this game (3 years ago), I was experimenting with different approaches:

1. Enter scores manually
2. Use dropdown with numbers (`0` - `20`)
3. Plus/Minus button

Users/friends told me that the Plus/Minus thing would be the easiest, "most natural" thing to do. So I adapted this pattern from last time. I even spoke to two UX/UI designers about this.

What would you say are the advantages of a text/number input?
The other way around, what are disadvantages of Plus/Minus?

**Comment by enderahmetyurt** [comment]
I guess input is more useful than clicking all time. For example I want to bet score like 4-5 I just click 9 times. Otherwise I click just 4 times. focus first input home write 4 and focus second input write 5. 
I dont see any disadvantages for input in web application. For mobile i am agree with you. In web in my personal experience I dont like to use clicking somewhere all time even if write it down in an input.

**Comment by enderahmetyurt** [comment]
@lxxxvi should I close it?

**Comment by lxxxvi** [comment]
@enderahmetyurt

I like your thinking and idea, and I am going to keep it in mind for next tournament (World Cup 2022, yay!). I even think it could work with both (or more) ways of entering a score, but for this tournament I'd just keep it as it is.

I don't mind keeping the issue open as a reminder, what do you think?

Speaking of... when it comes to implementing the next tournament's version, would you be interested in helping?

**Comment by enderahmetyurt** [comment]
okey. it sounds good. I can help about it whenever you want 👍

**Comment by enderahmetyurt** [comment]
<img src="https://media0.giphy.com/media/XbU7O23KKKZqcXIhLZ/giphy.gif"/>

**Comment by lxxxvi** [comment]
Thanks @enderahmetyurt 😄
