### ISSUE TITLE
Not loading postcss-loader/src/index.js

### ISSUE THREAD

**Issue by enderahmetyurt** [lxxxvi/tippkick.club#122]
After I fetched main branch from upstream postcss cannot be loaded in my locale.

![Screen Shot 2021-06-13 at 22 22 52](https://user-images.githubusercontent.com/447588/121819509-20a86680-cc96-11eb-96c9-dce6cc671f2b.png)
![Screen Shot 2021-06-13 at 22 23 11](https://user-images.githubusercontent.com/447588/121819511-21d99380-cc96-11eb-9dae-3fe0a30e88bc.png)

do u have any idea @lxxxvi ?

**Comment by lxxxvi** [comment]
@enderahmetyurt 
This looks not the way it should 😃

Do you have `bin/webpack-dev-server` running next to `bin/rails server` ?

Else you could try the classic:

* `rm -rf ./node_modules/; yarn install`

And/or clear some caches:

* `bin/rails tmp:clear`
* `rm -rf ./public/packs/; rm ./public/packs-test/`
