### ISSUE TITLE
World cup :)

### ISSUE THREAD

**Issue by enderahmetyurt** [lxxxvi/tippkick.club#130]
So what do you think about worldcup :) @lxxxvi

**Comment by lxxxvi** [comment]
Hi @enderahmetyurt ! Thanks for asking, I decided (for myself) to not do it this year. Feel free to fork and host it though. 😄

**Comment by enderahmetyurt** [comment]
Sorry to hear that. :( Yes, I would have forked this if I had remembered earlier. Only a few days left until the tournament arrives. I don't think I can finish before the cup starts. 😶‍🌫️
